export enum ErrorCode {
  // Generic
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  ENV_VALIDATION_ERROR = 'ENV_VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',

  // Auth domain
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_EMAIL_ALREADY_VERIFIED = 'AUTH_EMAIL_ALREADY_VERIFIED',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_USED = 'AUTH_TOKEN_USED',

  // User domain
  USER_PASSWORD_SAME = 'USER_PASSWORD_SAME',
  USER_PASSWORD_INVALID = 'USER_PASSWORD_INVALID',

  // Email domain
  EMAIL_SEND_FAILED = 'EMAIL_SEND_FAILED',

  // Master Data domain
  MASTER_DATA_COUNTRY_NOT_FOUND = 'MASTER_DATA_COUNTRY_NOT_FOUND',
  MASTER_DATA_COUNTRY_ALREADY_EXISTS = 'MASTER_DATA_COUNTRY_ALREADY_EXISTS',
  MASTER_DATA_CITY_NOT_FOUND = 'MASTER_DATA_CITY_NOT_FOUND',
  MASTER_DATA_CITY_ALREADY_EXISTS = 'MASTER_DATA_CITY_ALREADY_EXISTS',
  MASTER_DATA_DISTRICT_NOT_FOUND = 'MASTER_DATA_DISTRICT_NOT_FOUND',
  MASTER_DATA_DISTRICT_ALREADY_EXISTS = 'MASTER_DATA_DISTRICT_ALREADY_EXISTS',
}

export type ErrorCodeString = `${ErrorCode}`;


