version: '3.8'

services:
  # P2A Core System Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: p2a-core-system
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 3000
      # Database
      DB_MASTER_HOST: postgres
      DB_MASTER_PORT: 5432
      DB_MASTER_USERNAME: ${DB_MASTER_USERNAME:-p2a_user}
      DB_MASTER_PASSWORD: ${DB_MASTER_PASSWORD:-p2a_password}
      DB_MASTER_DATABASE: ${DB_MASTER_DATABASE:-p2a_core}
      DB_SYNCHRONIZE: ${DB_SYNCHRONIZE:-true}
      DB_LOGGING: ${DB_LOGGING:-false}
      # JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-30d}
      # Email
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME:-P2A ASEAN Platform}
      EMAIL_VERIFICATION_URL: ${EMAIL_VERIFICATION_URL}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - p2a-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: p2a-core-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_MASTER_USERNAME:-p2a_user}
      POSTGRES_PASSWORD: ${DB_MASTER_PASSWORD:-p2a_password}
      POSTGRES_DB: ${DB_MASTER_DATABASE:-p2a_core}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
      TZ: UTC
      PGTZ: UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - p2a-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_MASTER_USERNAME:-p2a_user} -d ${DB_MASTER_DATABASE:-p2a_core}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # pgAdmin (Optional - for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: p2a-core-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@p2a.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - p2a-network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  p2a-network:
    driver: bridge

